### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/infografia-de-las-librerias-garaudy12#2]
![Infografia Topicos](https://user-images.githubusercontent.com/37483714/114754230-f4b44780-9d1d-11eb-9bf9-8338637cf0eb.jpg)

**Comment by Rigoberto2001** [comment]
CALIFICACION: 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
